# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-20 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0049_rackreservation_change_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='coordinates',
            field=models.CharField(blank=True, max_length=16, verbose_name='Topology coordinates'),
        ),
    ]
