# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0054_site_status_timezone_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='coordinates',
            field=models.CharField(blank=True, max_length=32, verbose_name='Topology coordinates'),
        ),
    ]
